name: instantdb_flutter
description: "A real-time, offline-first database client for Flutter with reactive bindings."
version: 0.2.4
homepage: https://github.com/pillowsoft/instantdb_flutter
repository: https://github.com/pillowsoft/instantdb_flutter
documentation: https://instantdb-flutter-docs.pages.dev

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  signals_flutter: ^6.0.2
  dio: ^5.7.0
  web_socket_channel: ^3.0.3

  # Local storage
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^1.0.1+1
  path: ^1.9.1

  # Utilities
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  crypto: ^3.0.5
  logging: ^1.2.0

  # Environment variables for testing
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

  # Testing
  mocktail: ^1.0.4
  sqflite_common_ffi: ^2.3.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
